/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testcheckWeatherData() {
        Library classUnderTest = new Library();
        int[]expectedMinAndMaxTemp = {51,72};
        assertArrayEquals(expectedMinAndMaxTemp,classUnderTest.checkWeatherData());
        assertT
    }
}
