/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.w3c.dom.ls.LSOutput;

import java.sql.Array;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;

public class Library {

    public int[] checkWeatherData() {
        // Daily average temperatures for Seattle, October 1-28 2017
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int maxTemp = 0;
        int minTemp = 0;
        HashSet<Integer> uniqueTemp = new HashSet<Integer>();

        //identify and store all unique temps in a Hashset
        for (int i = 0; i < weeklyMonthTemperatures.length; i++) {
            for (int j = 0; j < weeklyMonthTemperatures[i].length; j++) {
                uniqueTemp.add(weeklyMonthTemperatures[i][j]);
            }
        }
        //create an ArrayList from hashset and sort it in order
        ArrayList<Integer> sortedTemp = new ArrayList<>(uniqueTemp);
        sortedTemp.sort(Comparator.naturalOrder());
        maxTemp = sortedTemp.get(sortedTemp.size() -1);
        minTemp = sortedTemp.get(0);

        System.out.println("Max Temp: " + maxTemp);
        System.out.println("Min Temp: " + minTemp);
        int[]minAndMaxTemp = {minTemp,maxTemp};
        identifyMissingTemps(minTemp,maxTemp,uniqueTemp);
        return minAndMaxTemp;
    }

    private static void identifyMissingTemps(int minTemp, int maxTemp, HashSet<Integer> uniqueTemp) {
        for(int i=minTemp; i<maxTemp; i++){
            if(!uniqueTemp.contains(i)) {
                System.out.println("Never saw temperature: " + i);
            }
        }
    }

}
